<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Setting;

class SettingSeeder extends Seeder
{
    public function run()
    {

        Setting::truncate();

        Setting::create([
            'key' => 'relationship_type',
            'value' => [
                "Marriage",
                "Friend",
                "Colleague",
            ],
        ]);
        Setting::create([
            'key' => 'subscribe_amount',
            'value' => [
                "1000",
            ],
        ]);
        Setting::create([
            'key' => 'address_verification_amount',
            'value' => [
                "600",
            ],
        ]);

        Setting::create([
            'key' => 'subscribe_day',
            'value' => [
                "7",
            ],
        ]);
        Setting::create([
            'key' => 'height_range',
            'value' => [
                "Under 4'0",
                "4'0 - 4'5",
                "4'6 - 4'11",
                "5'0 - 5'5",
                "5'6 - 5'11",
                "6'0 - 6'5",
                "6'6 - 6'11",
                "7'0 and above"
            ],
        ]);

        Setting::create([
            'key' => 'weight_range',
            'value' => [
                "Under 40kg",
                "40-49kg",
                "50-59kg",
                "60-69kg",
                "70-79kg",
                "80-89kg",
                "90-99kg",
                "100-109kg",
                "110-119kg",
                "120kg and above"
            ],
        ]);

        Setting::create([
            'key' => 'age_range',
            'value' => [
                "18-24",
                "25-29",
                "30-34",
                "35-39",
                "40-44",
                "45-49",
                "50-54",
                "55-59",
                "60+"
            ],
        ]);

        Setting::create([
            'key' => 'ethnicity',
            'value' => ["Yoruba", "Igbo", "Hausa", "Other"],
        ]);

        Setting::create([
            "key" => "marital_status",
            "value" => ["Single", "Married", "Divorced", "Widowed", "Separated"]
        ]);

        Setting::create([
            "key" => "nationality",
            "value" => [
                "Nigeria" => [
                    "nationality" => "Nigerian",
                    "states" => [
                        "Abia",
                        "Adamawa",
                        "Akwa Ibom",
                        "Anambra",
                        "Bauchi",
                        "Bayelsa",
                        "Benue",
                        "Borno",
                        "Cross River",
                        "Delta",
                        "Ebonyi",
                        "Edo",
                        "Ekiti",
                        "Enugu",
                        "Gombe",
                        "Imo",
                        "Jigawa",
                        "Kaduna",
                        "Kano",
                        "Katsina",
                        "Kebbi",
                        "Kogi",
                        "Kwara",
                        "Lagos",
                        "Nasarawa",
                        "Niger",
                        "Ogun",
                        "Ondo",
                        "Osun",
                        "Oyo",
                        "Plateau",
                        "Rivers",
                        "Sokoto",
                        "Taraba",
                        "Yobe",
                        "Zamfara",
                        "Federal Capital Territory (FCT)"
                    ],
                    "lgas" => [
                        "Abia" => [
                            "Aba North",
                            "Aba South",
                            "Arochukwu",
                            "Bende",
                            "Ikwuano",
                            "Isiala Ngwa North",
                            "Isiala Ngwa South",
                            "Isuikwuato",
                            "Obi Ngwa",
                            "Ohafia",
                            "Osisioma",
                            "Ugwunagbo",
                            "Ukwa East",
                            "Ukwa West",
                            "Umuahia North",
                            "Umuahia South",
                            "Umu Nneochi"
                        ],
                        "Adamawa" => [
                            "Demsa",
                            "Fufore",
                            "Ganye",
                            "Gayuk",
                            "Gombi",
                            "Grie",
                            "Hong",
                            "Jada",
                            "Lamurde",
                            "Madagali",
                            "Maiha",
                            "Mayo-Belwa",
                            "Michika",
                            "Mubi North",
                            "Mubi South",
                            "Numan",
                            "Shelleng",
                            "Song",
                            "Toungo",
                            "Yola North",
                            "Yola South"
                        ],
                        "Akwa Ibom" => [
                            "Abak",
                            "Eastern Obolo",
                            "Eket",
                            "Esit Eket",
                            "Essien Udim",
                            "Etim Ekpo",
                            "Etinan",
                            "Ibeno",
                            "Ibesikpo Asutan",
                            "Ibiono-Ibom",
                            "Ika",
                            "Ikono",
                            "Ikot Abasi",
                            "Ikot Ekpene",
                            "Ini",
                            "Itu",
                            "Mbo",
                            "Mkpat-Enin",
                            "Nsit-Atai",
                            "Nsit-Ibom",
                            "Nsit-Ubium",
                            "Obot Akara",
                            "Okobo",
                            "Onna",
                            "Oron",
                            "Oruk Anam",
                            "Udung-Uko",
                            "Ukanafun",
                            "Uruan",
                            "Urue-Offong/Oruko",
                            "Uyo"
                        ],
                        "Anambra" => [
                            "Aguata",
                            "Anambra East",
                            "Anambra West",
                            "Anaocha",
                            "Awka North",
                            "Awka South",
                            "Ayamelum",
                            "Dunukofia",
                            "Ekwusigo",
                            "Idemili North",
                            "Idemili South",
                            "Ihiala",
                            "Njikoka",
                            "Nnewi North",
                            "Nnewi South",
                            "Ogbaru",
                            "Onitsha North",
                            "Onitsha South",
                            "Orumba North",
                            "Orumba South",
                            "Oyi"
                        ],
                        "Bauchi" => [
                            "Alkaleri",
                            "Bauchi",
                            "Bogoro",
                            "Damban",
                            "Darazo",
                            "Dass",
                            "Gamawa",
                            "Ganjuwa",
                            "Giade",
                            "Itas/Gadau",
                            "Jama'are",
                            "Katagum",
                            "Kirfi",
                            "Misau",
                            "Ningi",
                            "Shira",
                            "Tafawa Balewa",
                            "Toro",
                            "Warji",
                            "Zaki"
                        ],
                        "Bayelsa" => [
                            "Brass",
                            "Ekeremor",
                            "Kolokuma/Opokuma",
                            "Nembe",
                            "Ogbia",
                            "Sagbama",
                            "Southern Ijaw",
                            "Yenagoa"
                        ],
                        "Benue" => [
                            "Ado",
                            "Agatu",
                            "Apa",
                            "Buruku",
                            "Gboko",
                            "Guma",
                            "Gwer East",
                            "Gwer West",
                            "Katsina-Ala",
                            "Konshisha",
                            "Kwande",
                            "Logo",
                            "Makurdi",
                            "Obi",
                            "Ogbadibo",
                            "Ohimini",
                            "Oju",
                            "Okpokwu",
                            "Otukpo",
                            "Tarka",
                            "Ukum",
                            "Ushongo",
                            "Vandeikya"
                        ],
                        "Borno" => [
                            "Abadam",
                            "Askira/Uba",
                            "Bama",
                            "Bayo",
                            "Biu",
                            "Chibok",
                            "Damboa",
                            "Dikwa",
                            "Gubio",
                            "Guzamala",
                            "Gwoza",
                            "Hawul",
                            "Jere",
                            "Kaga",
                            "Kala/Balge",
                            "Konduga",
                            "Kukawa",
                            "Kwaya Kusar",
                            "Mafa",
                            "Magumeri",
                            "Maiduguri",
                            "Marte",
                            "Mobbar",
                            "Monguno",
                            "Ngala",
                            "Nganzai",
                            "Shani"
                        ],
                        "Cross River" => [
                            "Akpabuyo",
                            "Odukpani",
                            "Akamkpa",
                            "Biase",
                            "Abi",
                            "Ikom",
                            "Yarkur",
                            "Odubra",
                            "Boki",
                            "Calabar South",
                            "Etung",
                            "Bekwarra",
                            "Bakassi",
                            "Obanliku",
                            "Obudu",
                            "Calabar Municipality"
                        ],
                        "Delta" => [
                            "Aniocha North",
                            "Aniocha South",
                            "Bomadi",
                            "Burutu",
                            "Ethiope East",
                            "Ethiope West",
                            "Ika North East",
                            "Ika South",
                            "Isoko North",
                            "Isoko South",
                            "Ndokwa East",
                            "Ndokwa West",
                            "Okpe",
                            "Oshimili North",
                            "Oshimili South",
                            "Patani",
                            "Sapele",
                            "Udu",
                            "Ughelli North",
                            "Ughelli South",
                            "Ukwuani",
                            "Uvwie",
                            "Warri North",
                            "Warri South",
                            "Warri South West"
                        ],
                        "Ebonyi" => [
                            "Abakaliki",
                            "Afikpo North",
                            "Afikpo South",
                            "Ebonyi",
                            "Ezza North",
                            "Ezza South",
                            "Ikwo",
                            "Ishielu",
                            "Ivo",
                            "Izzi",
                            "Ohaozara",
                            "Ohaukwu",
                            "Onicha"
                        ],
                        "Edo" => [
                            "Akoko-Edo",
                            "Egor",
                            "Esan Central",
                            "Esan North-East",
                            "Esan South-East",
                            "Esan West",
                            "Etsako Central",
                            "Etsako East",
                            "Etsako West",
                            "Igueben",
                            "Oredo",
                            "Orhionmwon",
                            "Ovia North-East",
                            "Ovia South-West",
                            "Owan East",
                            "Owan West",
                            "Uhunmwonde"
                        ],
                        "Ekiti" => [
                            "Ado Ekiti",
                            "Efon",
                            "Ekiti East",
                            "Ekiti South-West",
                            "Ekiti West",
                            "Emure",
                            "Gbonyin",
                            "Ido/Osi",
                            "Ijero",
                            "Ikere",
                            "Ikole",
                            "Ilejemeje",
                            "Irepodun/Ifelodun",
                            "Ise/Orun",
                            "Moba",
                            "Oye"
                        ],
                        "Enugu" => [
                            "Aninri",
                            "Awgu",
                            "Enugu East",
                            "Enugu North",
                            "Enugu South",
                            "Ezeagu",
                            "Igbo Etiti",
                            "Igbo Eze North",
                            "Igbo Eze South",
                            "Isi Uzo",
                            "Nkanu East",
                            "Nkanu West",
                            "Nsukka",
                            "Oji River",
                            "Udenu",
                            "Udi",
                            "Uzo-Uwani"
                        ],
                        "Gombe" => [
                            "Akko",
                            "Balanga",
                            "Billiri",
                            "Dukku",
                            "Funakaye",
                            "Gombe",
                            "Kaltungo",
                            "Kwami",
                            "Nafada/Bajoga",
                            "Yamaltu/Deba"
                        ],
                        "Imo" => [
                            "Aboh Mbaise",
                            "Ahiazu Mbaise",
                            "Ehime Mbano",
                            "Ezinihitte",
                            "Ideato North",
                            "Ideato South",
                            "Ihitte/Uboma",
                            "Ikeduru",
                            "Isiala Mbano",
                            "Isu",
                            "Mbaitoli",
                            "Ngor Okpala",
                            "Njaba",
                            "Nkwerre",
                            "Nwangele",
                            "Obowo",
                            "Oguta",
                            "Ohaji/Egbema",
                            "Okigwe",
                            "Onuimo",
                            "Orlu",
                            "Orsu",
                            "Oru East",
                            "Oru West",
                            "Owerri Municipal",
                            "Owerri North",
                            "Owerri West"
                        ],
                        "Jigawa" => [
                            "Auyo",
                            "Babura",
                            "Biriniwa",
                            "Birnin Kudu",
                            "Buji",
                            "Dutse",
                            "Gagarawa",
                            "Garki",
                            "Gumel",
                            "Guri",
                            "Gwaram",
                            "Gwiwa",
                            "Hadejia",
                            "Jahun",
                            "Kafin Hausa",
                            "Kaugama",
                            "Kazaure",
                            "Kiri Kasama",
                            "Kiyawa",
                            "Maigatari",
                            "Malam Madori",
                            "Miga",
                            "Ringim",
                            "Roni",
                            "Sule Tankarkar",
                            "Taura",
                            "Yankwashi"
                        ],
                        "Kaduna" => [
                            "Birnin Gwari",
                            "Chikun",
                            "Giwa",
                            "Igabi",
                            "Ikara",
                            "Jaba",
                            "Jema'a",
                            "Kachia",
                            "Kaduna North",
                            "Kaduna South",
                            "Kagarko",
                            "Kajuru",
                            "Kaura",
                            "Kauru",
                            "Kubau",
                            "Kudan",
                            "Lere",
                            "Makarfi",
                            "Sabon Gari",
                            "Sanga",
                            "Soba",
                            "Zangon Kataf",
                            "Zaria"
                        ],
                        "Kano" => [
                            "Ajingi",
                            "Albasu",
                            "Bagwai",
                            "Bebeji",
                            "Bichi",
                            "Bunkure",
                            "Dala",
                            "Dambatta",
                            "Dawakin Kudu",
                            "Dawakin Tofa",
                            "Doguwa",
                            "Fagge",
                            "Gabasawa",
                            "Garko",
                            "Garun Mallam",
                            "Gaya",
                            "Gezawa",
                            "Gwale",
                            "Gwarzo",
                            "Kabo",
                            "Kano Municipal",
                            "Karaye",
                            "Kibiya",
                            "Kiru",
                            "Kumbotso",
                            "Kunchi",
                            "Kura",
                            "Madobi",
                            "Makoda",
                            "Minjibir",
                            "Nasarawa",
                            "Rano",
                            "Rimin Gado",
                            "Rogo",
                            "Shanono",
                            "Sumaila",
                            "Takai",
                            "Tarauni",
                            "Tofa",
                            "Tsanyawa",
                            "Tudun Wada",
                            "Ungogo",
                            "Warawa",
                            "Wudil"
                        ],
                        "Katsina" => [
                            "Bakori",
                            "Batagarawa",
                            "Batsari",
                            "Baure",
                            "Bindawa",
                            "Charanchi",
                            "Dandume",
                            "Danja",
                            "Dan Musa",
                            "Daura",
                            "Dutsi",
                            "Dutsin Ma",
                            "Faskari",
                            "Funtua",
                            "Ingawa",
                            "Jibia",
                            "Kafur",
                            "Kaita",
                            "Kankara",
                            "Kankia",
                            "Katsina",
                            "Kurfi",
                            "Kusada",
                            "Mai'Adua",
                            "Malumfashi",
                            "Mani",
                            "Mashi",
                            "Matazu",
                            "Musawa",
                            "Rimi",
                            "Sabuwa",
                            "Safana",
                            "Sandamu",
                            "Zango"
                        ],
                        "Kebbi" => [
                            "Aleiro",
                            "Arewa Dandi",
                            "Argungu",
                            "Augie",
                            "Bagudo",
                            "Birnin Kebbi",
                            "Bunza",
                            "Dandi",
                            "Fakai",
                            "Gwandu",
                            "Jega",
                            "Kalgo",
                            "Koko/Besse",
                            "Maiyama",
                            "Ngaski",
                            "Sakaba",
                            "Shanga",
                            "Suru",
                            "Wasagu/Danko",
                            "Yauri",
                            "Zuru"
                        ],
                        "Kogi" => [
                            "Adavi",
                            "Ajaokuta",
                            "Ankpa",
                            "Bassa",
                            "Dekina",
                            "Ibaji",
                            "Idah",
                            "Igalamela-Odolu",
                            "Ijumu",
                            "Kabba/Bunu",
                            "Kogi",
                            "Mopa-Muro",
                            "Ofu",
                            "Ogori/Magongo",
                            "Okehi",
                            "Okene",
                            "Olamaboro",
                            "Omala",
                            "Yagba East",
                            "Yagba West"
                        ],
                        "Kwara" => [
                            "Asa",
                            "Baruten",
                            "Edu",
                            "Ekiti",
                            "Ifelodun",
                            "Ilorin East",
                            "Ilorin South",
                            "Ilorin West",
                            "Irepodun",
                            "Isin",
                            "Kaiama",
                            "Moro",
                            "Offa",
                            "Oke Ero",
                            "Oyun",
                            "Pategi"
                        ],
                        "Lagos" => [
                            "Agege",
                            "Ajeromi-Ifelodun",
                            "Alimosho",
                            "Amuwo-Odofin",
                            "Apapa",
                            "Badagry",
                            "Epe",
                            "Eti-Osa",
                            "Ibeju-Lekki",
                            "Ifako-Ijaiye",
                            "Ikeja",
                            "Ikorodu",
                            "Kosofe",
                            "Lagos Island",
                            "Lagos Mainland",
                            "Mushin",
                            "Ojo",
                            "Oshodi-Isolo",
                            "Shomolu",
                            "Surulere"
                        ],
                        "Nasarawa" => [
                            "Akwanga",
                            "Awe",
                            "Doma",
                            "Karu",
                            "Keana",
                            "Keffi",
                            "Kokona",
                            "Lafia",
                            "Nasarawa",
                            "Nasarawa Egon",
                            "Obi",
                            "Toto",
                            "Wamba"
                        ],
                        "Niger" => [
                            "Agaie",
                            "Agwara",
                            "Bida",
                            "Borgu",
                            "Bosso",
                            "Chanchaga",
                            "Edati",
                            "Gbako",
                            "Gurara",
                            "Katcha",
                            "Kontagora",
                            "Lapai",
                            "Lavun",
                            "Magama",
                            "Mariga",
                            "Mashegu",
                            "Mokwa",
                            "Muya",
                            "Paikoro",
                            "Rafi",
                            "Rijau",
                            "Shiroro",
                            "Suleja",
                            "Tafa",
                            "Wushishi"
                        ],
                        "Ogun" => [
                            "Abeokuta North",
                            "Abeokuta South",
                            "Ado-Odo/Ota",
                            "Egbado North",
                            "Egbado South",
                            "Ewekoro",
                            "Ifo",
                            "Ijebu East",
                            "Ijebu North",
                            "Ijebu North East",
                            "Ijebu Ode",
                            "Ikenne",
                            "Imeko Afon",
                            "Ipokia",
                            "Obafemi Owode",
                            "Odogbolu",
                            "Ogun Waterside",
                            "Remo North",
                            "Shagamu"
                        ],
                        "Ondo" => [
                            "Akoko North-East",
                            "Akoko North-West",
                            "Akoko South-West",
                            "Akoko South-East",
                            "Akure North",
                            "Akure South",
                            "Ese Odo",
                            "Idanre",
                            "Ifedore",
                            "Ilaje",
                            "Ile Oluji/Okeigbo",
                            "Irele",
                            "Odigbo",
                            "Okitipupa",
                            "Ondo East",
                            "Ondo West",
                            "Ose",
                            "Owo"
                        ],
                        "Osun" => [
                            "Aiyedaade",
                            "Aiyedire",
                            "Atakunmosa East",
                            "Atakunmosa West",
                            "Boluwaduro",
                            "Boripe",
                            "Ede North",
                            "Ede South",
                            "Egbedore",
                            "Ejigbo",
                            "Ife Central",
                            "Ife East",
                            "Ife North",
                            "Ife South",
                            "Ifedayo",
                            "Ifelodun",
                            "Ila",
                            "Ilesa East",
                            "Ilesa West",
                            "Irepodun",
                            "Irewole",
                            "Isokan",
                            "Iwo",
                            "Obokun",
                            "Odo Otin",
                            "Ola Oluwa",
                            "Olorunda",
                            "Oriade",
                            "Orolu",
                            "Osogbo"
                        ],
                        "Oyo" => [
                            "Afijio",
                            "Akinyele",
                            "Atiba",
                            "Atisbo",
                            "Egbeda",
                            "Ibadan North",
                            "Ibadan North-East",
                            "Ibadan North-West",
                            "Ibadan South-East",
                            "Ibadan South-West",
                            "Ibarapa Central",
                            "Ibarapa East",
                            "Ibarapa North",
                            "Ido",
                            "Irepo",
                            "Iseyin",
                            "Itesiwaju",
                            "Iwajowa",
                            "Kajola",
                            "Lagelu",
                            "Ogbomosho North",
                            "Ogbomosho South",
                            "Ogo Oluwa",
                            "Olorunsogo",
                            "Oluyole",
                            "Ona Ara",
                            "Orelope",
                            "Ori Ire",
                            "Oyo East",
                            "Oyo West",
                            "Saki East",
                            "Saki West",
                            "Surulere"
                        ],
                        "Plateau" => [
                            "Barkin Ladi",
                            "Bassa",
                            "Bokkos",
                            "Jos East",
                            "Jos North",
                            "Jos South",
                            "Kanam",
                            "Kanke",
                            "Langtang North",
                            "Langtang South",
                            "Mangu",
                            "Mikang",
                            "Pankshin",
                            "Qua'an Pan",
                            "Riyom",
                            "Shendam",
                            "Wase"
                        ],
                        "Rivers" => [
                            "Abua/Odual",
                            "Ahoada East",
                            "Ahoada West",
                            "Akuku-Toru",
                            "Andoni",
                            "Asari-Toru",
                            "Bonny",
                            "Degema",
                            "Eleme",
                            "Emohua",
                            "Etche",
                            "Gokana",
                            "Ikwerre",
                            "Khana",
                            "Obio/Akpor",
                            "Ogba/Egbema/Ndoni",
                            "Ogu/Bolo",
                            "Okrika",
                            "Omuma",
                            "Opobo/Nkoro",
                            "Oyigbo",
                            "Port Harcourt",
                            "Tai"
                        ],
                        "Sokoto" => [
                            "Binji",
                            "Bodinga",
                            "Dange Shuni",
                            "Gada",
                            "Goronyo",
                            "Gudu",
                            "Gwadabawa",
                            "Illela",
                            "Kebbe",
                            "Kware",
                            "Rabah",
                            "Sabon Birni",
                            "Shagari",
                            "Silame",
                            "Sokoto North",
                            "Sokoto South",
                            "Tambuwal",
                            "Tangaza",
                            "Tureta",
                            "Wamako",
                            "Wurno",
                            "Yabo"
                        ],
                        "Taraba" => [
                            "Ardo Kola",
                            "Bali",
                            "Donga",
                            "Gashaka",
                            "Gassol",
                            "Ibi",
                            "Jalingo",
                            "Karim Lamido",
                            "Kumi",
                            "Lau",
                            "Sardauna",
                            "Takum",
                            "Ussa",
                            "Wukari",
                            "Yorro",
                            "Zing"
                        ],
                        "Yobe" => [
                            "Bade",
                            "Bursari",
                            "Damaturu",
                            "Fika",
                            "Fune",
                            "Geidam",
                            "Gujba",
                            "Gulani",
                            "Jakusko",
                            "Karasuwa",
                            "Machina",
                            "Nangere",
                            "Nguru",
                            "Potiskum",
                            "Tarmuwa",
                            "Yunusari",
                            "Yusufari"
                        ],
                        "Zamfara" => [
                            "Anka",
                            "Bakura",
                            "Bungudu",
                            "Gummi",
                            "Gusau",
                            "Isa",
                            "Kiyawa",
                            "Maradun",
                            "Maru",
                            "Shinkafi",
                            "Talata Mafara",
                            "Chafe",
                            "Zurmi"
                        ],
                        "Federal Capital Territory (FCT)" => [
                            "Abaji",
                            "Bwari",
                            "Gwagwalada",
                            "Kuje",
                            "Kwali",
                            "Municipal Area Council"
                        ]
                    ]
                ]
            ]
        ]);


        Setting::create([
            "key" => "hobbies",
            "value" => [
                "Reading",
                "Traveling",
                "Cooking",
                "Swimming",
                "Gaming",
                "Cycling",
                "Dancing",
                "Drawing",
                "Photography",
                "Hiking",
                "Writing",
                "Watching Movies",
                "Listening to Music",
                "Gardening",
                "Singing",
                "Crafting",
                "Fishing",
                "Yoga",
                "Martial Arts",
                "Volunteering",
                "Collecting Antiques",
                "Bird Watching",
                "Board Games",
                "Knitting",
                "Learning Languages",
                "Painting",
                "Playing Musical Instruments",
                "Chess",
                "Running",
                "Meditation",
                "DIY Projects",
                "Blogging",
                "Podcasting",
                "Astronomy",
                "Scuba Diving",
                "Archery",
                "Pottery",
                "Stand-up Comedy",
                "Magic Tricks",
                "Urban Exploration"
            ]
        ]);

        Setting::create([
            "key" => "interests",
            "value" => [
                "Technology",
                "Sports",
                "Health & Fitness",
                "Art & Design",
                "Music",
                "Science",
                "Movies & TV Shows",
                "Travel",
                "Food & Drink",
                "Business & Finance",
                "Photography",
                "History",
                "Literature",
                "Politics",
                "Social Media",
                "Gaming",
                "Education",
                "Psychology",
                "Nature & Environment",
                "Animals & Pets",
                "Culture & Society",
                "Current Affairs",
                "Fashion & Beauty",
                "Self-improvement",
                "Spirituality",
                "Artificial Intelligence",
                "Renewable Energy",
                "Space Exploration",
                "Neuroscience",
                "Blockchain",
                "Sustainable Living",
                "Mental Health Awareness",
                "Human Rights",
                "Entrepreneurship",
                "Architecture",
                "Culinary Arts",
                "Anthropology",
                "Robotics",
                "Virtual Reality",
                "Minimalism"
            ]
        ]);

        Setting::create([
            "key" => "language_spoken",
            "value" => [
                "English",
                "Hausa",
                "Igbo",
                "Yoruba",
                "Spanish",
                "French",
                "German",
                "Italian",
                "Mandarin",
                "Hindi",
                "Arabic",
                "Russian",
                "Portuguese",
                "Japanese",
                "Korean",
                "Dutch",
                "Swedish",
                "Turkish",
                "Bengali",
                "Punjabi",
                "Urdu",
                "Swahili",
                "Vietnamese",
                "Greek",
                "Thai",
                "Hebrew",
                "Polish",
                "Romanian",
                "Czech",
                "Hungarian",
                "Finnish",
                "Danish",
                "Norwegian",
                "Filipino",
                "Malay",
                "Indonesian",
                "Persian",
                "Ukrainian",
                "Cantonese",
                "Tamil",
                "Telugu",
                "Gujarati",
                "Marathi",
                "Zulu",
                "Afrikaans",
                "Albanian",
                "Armenian",
                "Bulgarian",
                "Catalan",
                "Croatian",
                "Estonian",
                "Georgian",
                "Icelandic",
                "Irish",
                "Kazakh",
                "Latvian",
                "Lithuanian",
                "Macedonian",
                "Maltese",
                "Serbian",
                "Slovak",
                "Slovenian",
                "Tagalog",
                "Belarusian",
                "Bosnian"
            ]
        ]);



        Setting::create([
            'key' => 'genotype',
            'value' => [
                "AA",
                "AS",
                "SS",
                "AC",
                "SC",
            ],
        ]);

        Setting::create([
            "key" => "religion",
            "value" => [
                "Christianity" => [
                    "denominations" => [
                        "Catholic",
                        "Eastern Orthodox",
                        "Oriental Orthodox",
                        "Protestant",
                        "Anglican",
                        "Pentecostal",
                        "Evangelical",
                        "Baptist",
                        "Methodist",
                        "Lutheran",
                        "Presbyterian",
                        "Reformed",
                        "Adventist",
                        "Jehovah's Witness",
                        "Seventh-day Adventist",
                        "Quaker",
                        "Mennonite",
                        "Church of Christ",
                        "Church of God",
                        "Apostolic",
                        "Charismatic",
                        "Non-denominational",
                        "Holiness Movement",
                        "Assemblies of God",
                        "Calvary Chapel",
                        "Christian Science",
                        "African Independent Churches",
                        "Messianic Judaism",
                        "Coptic Church",
                        "Orthodox Church in America",
                        "United Church of Christ",
                        "Disciples of Christ",
                        "Salvation Army",
                        "Unitarian Universalism",
                        "Others"
                    ]
                ],
                "Islam" => [
                    "denominations" => [
                        "Sunni",
                        "Shia",
                        "Ahmadiyya",
                        "Ibadi",
                        "Others"
                    ]
                ],


            ]
        ]);

        Setting::create([
            'key' => 'gender',
            'value' => [
                "Male",
                "Female",
            ],
        ]);
    }
}
